- ezdxf/addons/table.py
> More linetype BYLAYER fixes.

- ezdxf/addons/table.py
> Fix table addon header twisted polygon.

- CHANGES_V10.md
- NEWS.md
- TODO.md
- docs/source/tutorials/linetypes.rst
- examples/render/dimension_linear.py
- ezdxf/entities/dictionary.py
- ezdxf/entities/dxfgfx.py
- ezdxf/entities/insert.py
- ezdxf/entities/polyline.py
- ezdxf/graphicsfactory.py
- ezdxf/math/bezier.py
- ezdxf/math/bspline.py
- ezdxf/math/line.py
- ezdxf/render/dimension.py
- tests/test_01_dxf_entities/test_115_new_empty_drawing.py
Found via `codespell -q 3 -S LICENSE.txt,./issues -L aci,ang`
> Misc. typos

- examples/import_dxf_via_browser.py
Hi Mozman, I believe I am doing the right thing the right way. I forked your ezdxf, then added a file to my Master and now I have created a pull request. Hope it helps. Joseph
> example import dxf file through browser

- src/ezdxf/math/vector.py
- tests/test_06_math/test_603_vec2.py
fixes https://github.com/mozman/ezdxf/issues/141
> fixed crash caused by floating point inaccuracy in angle_between

- docs/source/addons/draw.rst
- src/ezdxf/addons/drawing/backend_interface.py
- src/ezdxf/addons/drawing/cad_viewer.py
- src/ezdxf/addons/drawing/colors.py
- src/ezdxf/addons/drawing/front_end.py
- src/ezdxf/addons/drawing/matplotlib_backend.py
- src/ezdxf/addons/drawing/pyqt_backend.py
- src/ezdxf/addons/drawing/test/test_backends.py
- src/ezdxf/addons/drawing/text.py
- src/ezdxf/addons/drawing/utils.py
- src/ezdxf/entities/mtext.py
a few small improvements and an attempt to prevent the backend test from crashing on Windows
> Drawing improvements

- src/ezdxf/addons/odafc.py
every version of ODAFileConverter that I have tried always crashes when run on linux with `Quit (core dumped)` written to stderr even when the conversion was successful. Because of this I relaxed the check for a successful run in the odafc addon.
I've tried creating a docker container with ODAFileConverter inside and even in this completely fresh environment it still crashes, but it seems to still be successful so these crashes can be ignored.
This change is mostly important for being able to load dwg files in the cad viewer in Linux.
> Workaround for ODAFileConverter always crashing on Linux

- src/ezdxf/acc/matrix44.pyx
- src/ezdxf/acc/vector.pyx
- tests/test_06_math/test_602_vec3.py
- tests/test_06_math/test_603_vec2.py
- tests/test_06_math/test_605_matrix44.py
- tests/test_06_math/test_649_nurbs_python_interface.py
added support for pickling the cython math classes since I knew it would be easy to do. Fixes #303
> Math pickling

- src/ezdxf/addons/drawing/text.py
this fixes #319. The behaviour is reverse-engineered from what I see from rendering the text stress test. I checked and the stress test covers all possible alignment values and since it renders correctly I assume the logic is correct.
@mozman do you know about any other edge cases that might not be covered? for example is `align_point` a valid attribute of ATTRIB? Also do you agree with the logic in `_get_wcs_insert`?
> improved TEXT alignment calculation

- examples/addons/drawing/cad_viewer.py
- src/ezdxf/addons/dxf2code.py
some really minor things that I fixed as I needed them.
I'm aware of a crash (segfault) that sometimes occurs in the cad_viewer when loading a new scene. Not sure if this only happens on Linux. I haven't looked into it.
> Small fixes

- src/ezdxf/math/__init__.py
- src/ezdxf/math/bezier4p.py
- tests/test_06_math/test_630b_bezier4p_functions.py
in my application I only want to have to support one type of bezier curve, so I needed a utility to convert quadratic curves in order to support the new `Command.CURVE3_TO`.
I might have not put the function in the right module. I can move it if you want.
> quadratic to cubic bezier utility

- docs/source/concepts/dxf.rst
Hello!
Here are a few small changes from a recent reading of the documentation.
Let me know if further changes needed.
> Minor updates to DXF documentation

- docs/source/tutorials/layers.rst
remove errant curly bracket on line 17
> Update layers tutorial

- examples/addons/r12writer_big_files.py
- examples/megagrid.py
- src/ezdxf/tools/text_layout.py
- tests/test_02_dxf_graphics/test_236_multileader.py
- tests/test_05_tools/test_515_fonts.py
- tests/test_05_tools/test_520_mtext_context.py
> Fix various source typos 

- docs/source/dxfentities/lwpolyline.rst
it's explained here: https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-20B4D4B3-1220-426A-847B-5BBE36EC6FDF-htm.html#GUID-20B4D4B3-1220-426A-847B-5BBE36EC6FDF__SECTION_C298CAFE7CDF42A1AF937862BDA04F1C
> PLINGEN attribute explained

- docs/source/tutorials/geo.rst
> shapley --> shapely

- README.md
Added three commands that I found useful following: https://github.com/mozman/ezdxf/discussions/331#discussioncomment-6369488
> Update README.md - Command Line section

- src/ezdxf/math/bspline.py
This finishes fixing #909—assuming this is how you would like to fix it.
> Loosen a couple of assertions in ezdxf.math.bspline

- src/ezdxf/addons/odafc.py
The warning:
```
odafc.py:145: ResourceWarning: unclosed file <_io.BufferedReader name=5>
_execute_odafc(args)
```
On POSIX using `subprocess.run` is simpler to use and reason about since it just blocks until the process returns.
> Fix ResourceWarning about unclosed file on POSIX

- src/ezdxf/addons/drawing/frontend.py
- src/ezdxf/addons/drawing/pymupdf.py
this adds support for rendering images in the muPDF backend.
I also improved the missing image text rendering a bit so the text should always have a reasonable size and is now centered where it should be. The output of mupdf is looking very nice :)
one issue is that mupdf seems to have issues with transparency gradients in images, but I don't think there is much ezdxf can do about that.
ezdxf + mupdf (to png)
reference (autocad)
> Drawing image support 2

- src/ezdxf/fonts/font_manager.py
do i need to update a version?
> Added additional dir for fonts on mac

- src/ezdxf/addons/dxf2code.py
- Fix infinite loop in `merge()` function
> Fix the infinite loop in `dxf2code.py`

- src/ezdxf/entities/insert.py
> Insert.add_auto_attribs() support MText attrs

- src/ezdxf/addons/odafc.py
> Use pid as display id in odafc #1235
