docs/source/tutorials/layers.rst
dwg is a Drawing object, to add lines you would need to create either a layout or a modelspace.
=>  AttributeError: 'Drawing' object has no attribute 'add_line'

NEWS.rst, README.rst, docs/notes/dimvars.txt, docs/source/addons/curves.rst, docs/source/algebra/vector.rst, docs/source/dxfinternals/block_management.rst, docs/source/dxfinternals/classes_section.rst, docs/source/dxfinternals/coordinate_systems.rst, docs/source/dxfinternals/layout_management.rst, docs/source/layouts.rst, docs/source/r12writer.rst, docs/source/tutorials/layers.rst, examples/addons/using_table_addon.py, examples/tut/spline/modified_spline.py, ezdxf/acadctb.py, ezdxf/addons/sierpinski_pyramid.py, ezdxf/addons/table.py, ezdxf/algebra/bspline.py, ezdxf/graphicsfactory.py, ezdxf/legacy/layouts.py, ezdxf/lldxf/extendedtags.py, ezdxf/modern/groups.py, ezdxf/modern/mleader.py, ezdxf/r12writer.py, ezdxf/sections/acdsdata.py, ezdxf/tools/complex_ltype.py, ezdxf/tools/juliandate.py, ezdxf/tools/perlin.py, tests/test_modern_structures/test_geodata.py
Found via `codespell -q 3 -I ../ezdxf-word-whitelist.txt` where the whitelist consists of:
```
aci
ang
oder
taget
unter
```
=> Misc. typo fixes

ezdxf/math/line.py, tests/test_06_math/test_641_construction_ray.py
Sometimes ConstructionLine has_intersect returns false when it should be true.
My construction line is horizontal on the line y=248.725, the point returned by self.ray.intersect has y=248.72500000000002. The point is therefore not in the bounding box and has_intersect returns true.
This change fixes my bug and should cover all edge cases I can think of.
=> Construction Line intersect bug

docs/source/tables/vport_table_entry.rst
"center_point" doesn't exist as dxf attribute of this class anymore and is now accessible as "center" attribute
=> Fix wrong reference to the "center_point" attribute

src/ezdxf/math/construct2d.py
Using ConstructionLine.intersect() I got no intersect where there should be one. 
My error was on the order of 5e-12
Perhaps 1e-10 would be safer though.
=> Tolerance too low

src/ezdxf/entities/insert.py, src/ezdxf/explode.py, tests/test_04_dxf_high_level_structs/test_414_explode_blockrefs.py
This pull request adds an interface for determining which entities are skipped during expansion of an Insert entity. The implementation perhaps isn't ideal, but it does limit the amount of change to the implementation of `virtual_block_reference_entities()`.
=> Return skipped entities

src/ezdxf/sections/acdsdata.py
I was trying to get ezdxf to compile with Cython and was getting this error:
File "acdsdata.py", line 172, in ezdxf.sections.acdsdata.AcDsRecord.__init__
UnboundLocalError: local variable 'tags' referenced before assignment
I was able to get it to compile by changing the duplicate variable name from tags to group.
Thanks for all your efforts on this awesome package!
Just in case you are interested: in my application, after compiling with Cython reading the DXF file is about 3x faster than with pure CPython 3.8.
=> Duplicate variable name broke Cython compatibility

src/ezdxf/addons/odafc.py
_odafc_cmd and ezdxf.readfile are expecting a str according to their type annotations. Passing them a Path object breaks Cython compatibility.
=> Passing Path object when str is expected

src/ezdxf/explode.py, src/ezdxf/math/__init__.py, src/ezdxf/math/construct2d.py, src/ezdxf/math/vector.py, tests/test_02_dxf_graphics/test_221_ellipse.py, tests/test_04_dxf_high_level_structs/test_414_explode_blockrefs.py, tests/test_06_math/test_602_vector.py
I ran into a problem where ellipses inside blocks were sometimes not rendering correctly. One problem contributing to this is that `angle_to_param()` seemed to be returning incorrect parameters for angles close to the boundaries of the quadrants. Replacing this function with my own implementation fixed that issue.
The unit test ensures that if the ratio is 1.0 then param == angle. Another part to the test is that regardless of other ellipse attributes like the choice of major axis, constructing an ellipse with a parameter calculated from an angle then using `ellipse.(start|end)_point` and getting the angle to that point should yield the original angle. This was not the case with the old implementation.
There were additional issues uncovered by the unit test relating to the fact that the …
=> Ellipse parameters

src/ezdxf/explode.py, src/ezdxf/math/vector.py, tests/test_04_dxf_high_level_structs/test_414_explode_blockrefs.py, tests/test_06_math/test_602_vector.py
I created this CAD file as reference and tried to match the behaviour when encountering reflections. Before my previous patch, the start and end locations were incorrect, after my ellipse patch the start and end points were correct but sometimes the wrong sides of the ellipses were drawn:
[rotated_and_scaled_arcs.dxf.zip](https://github.com/mozman/ezdxf/files/4563963/rotated_and_scaled_arcs.dxf.zip)
AutoCad:
My rendering after the ellipses patch:
After applying this patch:
so the ellipses/arcs are correct for all the zscale > 0 cases.
I tried several approaches including negating the extrusion vector, but I found that if a reflected block is exploded in autocad, the extrusion vector is not negated, so instead the ellipse parameters just have to be interpreted differently in the case where …
=> Fix reflections

src/ezdxf/addons/odafc.py
I saw some activity from pull requests to get the oda file converter addon working on Linux. I have already solved the GUI problem for linux and thought I should share my findings.
Since ezdxf seems to prefer fewer dependencies I didn't use the xvfbwrapper python package but instead wrote a minimal xvfb interface to allow the ODAFileConverter to run inside a dummy X display.
While I was at it I did some refactoring, added some more checks for files already existing and used `shutil.which()` which avoids hard coding paths for linux and hopefully OSX (but Windows might still require the hard coded path). Also TemporaryDirectory is a good cross platform way of obtaining a temporary directory rather than hard coding anything.
=> odafc addon improvements

examples/addons/drawing/cad_viewer.py, src/ezdxf/addons/drawing/debug_utils.py, src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/properties.py, src/ezdxf/addons/drawing/text.py, tests/test_08_addons/test_811_drawing_frontend.py
I think it makes sense for the override interface to be implemented by inheriting from the frontend. Do you agree? I think in most cases the front end is a single-use object so assigning different override functions to it seems unnecessary. Also, by making it a method of the frontend, the filter has access to the current rendering context as well which could be useful.
I also moved the hack to set hatch transparency into the override method since that is a good use case for this method, and it means that the value returned from `resolve_color` is accurate. I also changed the skip_entity interface to pass in the entity itself which is more useful than just a message.
=> Improved override and skip entity interfaces

src/ezdxf/entities/mtext.py, tests/test_02_dxf_graphics/test_225_mtext.py
I was generating a dxf file and comparing the output in autocad vs cad_viewer and found that one of the MText entities wasn't being drawn. I looked into it and found the cause was an invalid escape code `\:` which I had accidentally introduced (but which wasn't causing any errors or warnings anywhere). In this situation AutoCAD renders the text as-is, whereas ezdxf returns `""` from `plain_text()`. This change returns the text as-is if a stacking command cannot be parsed before the end of the string.
```python
import ezdxf
if __name__ == '__main__':
doc = ezdxf.new()
msp = doc.modelspace()
t = msp.add_mtext('\\: abcdef')
print(t.plain_text())
```
=> handling of invalid escape codes

examples_dxf/caret_encoding.dxf, examples_dxf/create_caret_encoding.py, src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/pyqt.py, src/ezdxf/entities/mtext.py, tests/test_02_dxf_graphics/test_225_mtext.py
earlier, support for `^M` and `^J` was added to ezdxf, however this is just a special case of a broader capability of the dxf format to encode characters in so-called '[caret notation](https://en.wikipedia.org/wiki/Caret_notation)'. For example `'^a' == '!'`
I have extended support to hopefully support any caret-encoded string that might be encountered. In the dxf files I have access to I have only seen `^J`, `^I` and `^ ` but full support is better. The `(c - 64) % 126` formula was reverse engineered from what I saw AutoCAD produce and looking at ASCII tables.
Decoding is now done in two steps, first the caret-encoded characters are decoded, then if those characters are newlines they are re-encoded in dxf encoding (`\P`).
Also, when drawing these strings, non-printable characters can be …
=> Added caret notation support

src/ezdxf/addons/drawing/backend.py, src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/pyqt.py, src/ezdxf/entities/mtext.py, src/ezdxf/entities/text.py, tests/test_02_dxf_graphics/test_206_text.py, tests/test_02_dxf_graphics/test_225_mtext.py
I realised that my last pull request left some things unfinished because TEXT entities should also support caret encoding.
It turns out that they do, but handle them slightly differently.
- non-printable characters are replaced with `?` rather than `▯`
- fewer characters are supported in TEXT, for example `\t` is replaced with `?`
- `\n` does have an effect, but seems to not be intended behaviour to allow this so I just remove `\n`
There is also a difference in that MText strings can end with a `^` and still be valid and rendered correctly, however a `Text` ending with `^` will be invalid and AutoCAD will refuse to load the file. I added a check for this during export but I'm not sure where the best place to put this check is, so you might want to move it.
AutoCAD rendering
ezdxf …
=> Added caret support in TEXT entity

docs/source/dxfobjects/geodata.rst, src/ezdxf/document.py, src/ezdxf/entities/geodata.py, tests/test_01_dxf_entities/houses_of_parliament_georeferenced.dxf, tests/test_01_dxf_entities/test_135_geo_data.py
after posting #214 I made a breakthrough in interpreting GeoData created by georeferencing in AutoCAD.
I realised that `source_vertices` and `target_vertices` are completely useless and have nothing to do with the particular CAD file in question, but rather they define the CRS transformation between the CRS of the GeoData and WGS84 (The sort of thing which can already be done by a library like `pyproj`).
I have added support for parsing the epsg number of the CRS from GeoData specified in the way that AutoCAD does it (as xml using what appears to be a custom format), and obtaining the transformation which transforms from WCS into that CRS.
There are a lot of checks to make sure that the GeoData is very similar to the ones that I have tested on, although some of those checks could probably …
=> added support for interpreting some kinds of geodata

src/ezdxf/addons/drawing/matplotlib.py
a few small things changed with the quick save utility:
- I am not sure if there would ever be a use for any rect other than (0, 0, 1, 1) since the image could just be loaded and manipulated afterwards if the user truly only wanted part of the image to be filled with the CAD drawing. If you think it would be useful then I can revert that change
- `transparent=True` sets the axis color to fully transparent and `facecolor=...` sets the figure color. If the output format doesn't support transparency then the output will just become opaque so I don't think there is a need to expose a parameter for `transparent`
- if neither `transparent` or `facecolor` is used then the output will be opaque even if the cad/axis background color is semi-transparent  
- if only transparent is used then the …
=> Qsave improvements

examples/addons/drawing/cad_viewer.py, src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/pyqt.py, src/ezdxf/addons/drawing/text.py
improving on  #234, this change introduces the capability for the Qt and matplotlib backends to cache paths for text.
The improvements aren't as dramatic as the 3x that @DGriffin91 obtained but there is a significant improvement anyway.
I also encountered a subtle bug because I was benchmarking with random strings. It turns out that even if `TextPath` is passed `usetex=False`, it will attempt to identify math text in between `$` characters like it would in tex mode. To avoid this, the matplotlib backend has to escape any `$` characters to `\$`. This change is included in this pull request.
reusing the matplotlib backend for different axes would be tricky since there is no `start_drawing()` to accompany `finalize()` and `finalize()` of the matplotlib backend alters some global state …
=> Text caching

src/ezdxf/addons/drawing/matplotlib.py
When writing my last pull request I noticed that `Line2D` was being used to draw the line segments of different linestyles. Matplotlib provides better tools for drawing many identical lines: `LineCollection`. This pull request makes use of this.
Using the script below which generates 1000 random lines of random line types, I benchmarked the internal line rendering against the `Line2D` and `LineCollection` based `ezdxf` renderers:
- internal: 0.7 seconds
- `Line2D`: 13 seconds
- `LineCollection`: 1.7 seconds
I think that a `Path` with `MOVETO` and `LINETO` commands could also work but I haven't tested that so I don't know if it would be faster than linecollection, but I think this speed is acceptable.
The output appears slightly different when using a LineCollection. I think this is due to …
=> improved performance of ezdxf linestyle rendering

src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/pyqt.py, src/ezdxf/addons/drawing/text.py, tests/test_08_addons/test_811_drawing_frontend.py
this pull request fixes rendering using a font which has a baseline other than y=0. This fixes #241.
The new approach is also slightly more efficient because the heights (i.e. distances from the baseline) are stored rather than the absolute y values. The text alignment only ever uses the heights anyway so it makes sense to store those rather than the y values.
in a non very rigorous test I rendered the `examples_dxf/text.dxf` before and after this change.
- if the font has baseline = 0 then the outputs are exactly identical (as expected)
- if the baseline is != 0 then the results are different. I used the `Gayathri` font family (because it was the first one I picked at random with a non-zero baseline) which has a baseline at -0.0117 and there were some very slight differences (tested …
=> added support for fonts with baselines other than y=0

src/ezdxf/addons/drawing/pyqt.py
a minor fix. I just realised that data roles less than `0x0100` (`Qt::UserRole`) shouldn't be used for application specific purposes:
https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum
=> small fix to use correct data roles

src/ezdxf/addons/drawing/frontend.py
sorry for not catching this when I implemented the dispatch table, but unlike the other methods, `draw_viewport_entity` does not take a `properties` parameter so trying to draw a viewport crashes.
=> fix for draw_viewport_entity

src/ezdxf/tools/text.py
Since support for columns is probably not coming soon (I don't have a particular need for them) it is better to at least replace `\N` with something sensible for the time being.
=> replace new column escape codes

src/ezdxf/addons/drawing/pyqt.py
In AutoCAD the hatch patterns are view dependent (you can zoom in on them), so this change moves away from 'compliance' slightly, but I think it's a better compromise since the highly scaled hatch patterns are too blurry. It would be tricky to choose the correct scale because that would rely on having perfect knowledge of the CAD file units. This approach should look the same in all CAD files regardless of their units / scale.
If you prefer the patterns to be scaled up slightly (too much and they would be blurry again) then a call to `scale()` of the inverted painter transform would apply that scale globally.
before:
after:
=> made Qt brushes cosmetic

docs/source/tutorials/src/hatch/solid_hatch_islands.py, docs/source/tutorials/src/hatch/solid_hatch_polyline_path.py, docs/source/tutorials/src/hatch/solid_hatch_polyline_path_with_bulge.py
The `is_closed` parameter expects a `bool` type. Update the Hatch tutorial to pass in `True` rather than `1`.
=> Pass True to boolean hatch example call rather than 1

src/ezdxf/lldxf/repair.py
Closes #371
Use [`warnings.filterwarnings`](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings) to suppress [`BytesWarning`](https://docs.python.org/3/library/exceptions.html#BytesWarning) at `import` time without changing the behaviour of the package.
This allows consumers of this package to continue to check their own code for `BytesWarning`s.
=> Fix BytesWarning thrown at import time in lldxf.repair.py

src/ezdxf/tools/__init__.py
Hi.
I am developing an application where I have to use this wonderful package and, simultaneously, load a .DLL using ctypes.
For some reason, if I used the .DLL, the code would exit without any error/exception. I've found out that the issue was on the ezdxf.toold.guid(), because it was using uuid1(). I don't now the exact details, but changing this to the uuid4() solved my problem. Bases on [this answer](https://stackoverflow.com/a/1785592) it should not be an issue.
Hope that a new version of ezdxf can be released quickly.
Thanks for this awesome package!
=> Fix issue with ezdxf.tools.guid()

docs/source/dxfentities/lwpolyline.rst
I always wondered what the `LW` in `LWPOLYLINE` was. I was able to find a reference that makes sense:
https://www.cadtutor.net/forum/topic/48794-what-is-a-lwpolyline/?do=findComment&comment=403240
> A lightweight polyline (lwpolyline) is defined in the drawing database as a single graphic entity. The lwpolyline differs from the old-style polyline, which is defined as a group of subentities. Lwpolylines display faster and consume less disk space and RAM.
A more authoritative source: http://docs.autodesk.com/ACDMAC/2014/ENU/index.html?url=files/GUID-0A3004D1-1BF6-468A-9F69-4D0BA88857F2.htm,topicNumber=d30e319257
>A lightweight polyline (lwpolyline) is defined in the drawing database as a single graphic entity unlike the old-style polyline, which is defined as a group of subentities.
> …
=> Define LW as Lightweight Polyline

src/ezdxf/addons/drawing/qtviewer.py
Since it was created, the cad_viewer had a problem where it occasionally crashes when loading a new document. The error wasn't in python so there was no traceback or anything which made it hard to debug so I left it.
The errors looked like
```
cad_viewer: line 11: 18408 Segmentation fault      (core dumped)
```
today I found that the crash can be triggered very consistently by creating a file like this:
```python
import ezdxf
if __name__ == '__main__':
doc = ezdxf.new()
layout = doc.modelspace()
d = 1
points = [(0, 0), (d, 0), (0, d), (d, d)]
for box_x in range(100):
for box_y in range(100):
box_points = [(x + box_x, y + box_y) for x, y in points]
s = layout.add_solid(box_points)
s.rgb = (box_x, box_y, 48)
doc.saveas('/tmp/boxes.dxf')
```
then opening it in the cad_viewer then repeatedly …
=> Fixed RuntimeError when loading new document in cad_viewer

src/ezdxf/addons/drawing/frontend.py, src/ezdxf/commands.py
Just a few small changes.
- If the current layout isn't set then the colors are not correct when drawing a paperspace layout.
- added the option to select the layout in the `view` and `draw` commands
- Another feature that I find useful (for debugging mainly) is to set all layers or all entities visible.
Feedback is welcome if you would do anything differently or don't want to include some of these options.
~note that because of https://github.com/mozman/ezdxf/issues/478 I haven't been able to test these changes.~
=> Draw improvements

MANIFEST.in, setup.py, src/ezdxf/py.typed
See https://www.python.org/dev/peps/pep-0561/
`mypy` and other type checkers use the presence of a `py.typed` file in the root of the package to signal that the package has inline type annotations to be used for type checking. Including this file allows users of this library to properly type check their usage of this package.
=> Include py.typed file in package to comply with PEP 561

src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/properties.py
for me, OLE2FRAME entities are are in the same category as Viewport: I don't really care what they contain but I would like to know that they are there.
Currently OLE2FRAME entities are skipped but I think it would be better for the frontend to handle these entities when identified. In the future someone could expand on the `draw_ole_frame_entity` method to draw the entity properly if they want to.
I know that this implementation isn't ideal as it reads dxf tags directly, but it's quite simple and adds the minimum support for the entity needed to draw it as a rectangle. If this isn't sufficient I can make some improvements with your guidance.
=> added basic OLE2FRAME drawing support

src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/properties.py, src/ezdxf/tools/pattern.py
fixes #508 by adding better control over the `LayoutProperties` used by the drawing frontend.
`RenderContext.set_current_layout()` isn't sufficient for full control over `LayoutProperties` since most attributes are not stored in the dxf object (eg background color) but are instead inferred. However the most common case is still to take the properties derived directly from a layout so I think it makes sense to keep this as a helper method?
Or you could remove `set_current_layout` and require using `ctx.current_layout = LayoutProperties.from_layout(mylayout)` which is still clear, but more verbose. Also I'm not sure about the name `current_layout` because it might imply the type is `Layout` rather than `LayoutProperties` but so long as the documentation is clear it shouldn't be an issue.
So …
=> Layout colors fix

src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/properties.py, src/ezdxf/entities/solid.py, tests/test_02_dxf_graphics/test_205_solid.py
The individual edges of a 3DFACE entity can be visible or hidden. Previously the `RenderContext` would cast `entity.dxf.invisible` to a bool to determine whether a 3DFACE is visible or not. For 3DFACE this field is a bit mask specifying the invisibility of each edge rather than the visibility of the entire entity, so if any edge was not visible the entire entity would be skipped.
With this pull request the entity is considered visible if any of it's edges are visible and the frontend considers two cases:
- the case where every edge is visible: draw as a path like before
- the case where one or more edges are invisible: draw the visible edges as individual lines
I did consider using `move_to` and always drawing as a path but that may complicate the backend as currently `move_to` commands …
=> 3DFACE: per edge visibility [WIP]

src/ezdxf/entities/solid.py, src/ezdxf/path/converter.py, tests/test_02_dxf_graphics/test_205_solid.py
the second part to #513 
With this change there is no distinction between a 3D face which represents a rectangle and one that represents a triangle. This means that a consistent number of vertices is returned from `wcs_vertices` which makes the edge visibility easier to interpret.
With this change the 3dface example renders exactly how it appears in autocad:
=> face3d always creates a consistent number of vertices

src/ezdxf/addons/drawing/backend.py, src/ezdxf/addons/drawing/config.py, src/ezdxf/addons/drawing/debug_utils.py, src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/line_renderer.py, src/ezdxf/addons/drawing/matplotlib.py, src/ezdxf/addons/drawing/mtext_complex.py, src/ezdxf/addons/drawing/properties.py, src/ezdxf/addons/drawing/pyqt.py, src/ezdxf/addons/drawing/qtviewer.py, src/ezdxf/addons/drawing/text.py, src/ezdxf/disassemble.py, src/ezdxf/render/dim_radius.py, tests/test_08_addons/test_811_drawing_frontend.py
following the discussion https://github.com/mozman/ezdxf/discussions/534 I have refactored the drawing addon configuration so that the backend is accessed through a strictly controlled interface rather than accessing and having the frontend and render context modify public attributes in-place.
The `Configuration` class is read only (frozen) so that the flow of data is easier to track. No longer can other parts of the system mutate values all over the place.
I also took the opportunity to replace some of the integer arguments with enums so that their possible values are clearer. I was not entirely sure about the purpose of some of the parameters, for example `lineweight_scale` vs `linetype_scale`. It seemed that `linetype_scale` is a hack where 1 => interpret line styles and 0 => draw …
=> improved configuration of the drawing addon

docs/source/launcher.rst
The result still doesn’t seem to work for me (on Fedora Linux 36) for reasons that seem to be related to quoting and/or argument splitting. I haven’t taken time to figure out exactly what is happening.
Still, this PR fixes the typo in the command path.
=> Fix typo in browse-command config example for gedit

docs/source/path.rst, src/ezdxf/path/converter.py, src/ezdxf/path/tools.py
1. converter.py: get segments from kwargs in 2/3 uses of add_2d_polyline (hatch doesn't have kwargs)
2. tools.py: add_2d_polyline(): bulge_to(): added segmentation of angles and loop
3. path.rst: Path Factory Function description added BULGE
=> for make_path() bulges respect segments except hatch

docs/source/tutorials/blocks.rst, docs/source/tutorials/custom_data.rst, docs/source/tutorials/mleader.rst, docs/source/tutorials/ucs_transform.rst
While reading the documents, I found some code refereces which were shifted by a line or had redundant new lines.
- https://ezdxf.readthedocs.io/en/stable/tutorials/blocks.html#using-attribute-definitions
- https://ezdxf.readthedocs.io/en/stable/tutorials/mleader.html (overall)
- https://ezdxf.readthedocs.io/en/stable/tutorials/ucs_transform.html#placing-lwpolyline-in-3d-space
- https://ezdxf.readthedocs.io/en/stable/tutorials/custom_data.html (XData, XRecord, AppData)
=> adjusted some code lines in documents

docs/source/usage_for_beginners.rst, examples/addons/drawing/cad_viewer.py, examples/addons/drawing/element_picker.py, src/ezdxf/addons/drawing/qtviewer.py, src/ezdxf/commands.py
Prompted by https://github.com/mozman/ezdxf/discussions/878 I had a go at creating a simple example of using the Qt drawing functionality to select an element but found that the code was not organised to make this very easy.
This PR splits out the cad widget functionality from CADViewer into a separate CADWidget class which is more suitable for embedding into other applications or injecting custom functionality (such as selecting elements).
There are also some other minor refactorings:
- renamed some `Cad*` classes to `CAD*` to match the convention elsewhere such as `DXFEntity` instead of `DxfEntity`
- fixed what I think is a typo in the beginner docs
- renamed the `element_selected` signal to `element_hovered` which is more specific
=> Configurable cad view

src/ezdxf/addons/drawing/qtviewer.py
adds functionality requested in https://github.com/mozman/ezdxf/discussions/874
adds a 'Reload' menu to the CAD viewer with the following options:
- `Reload (F5)` immediately reloads the current CAD document
- `Keep View` choose whether the view is retained or reset when the document is reloaded
- `Watch` automatically reload if the file changes
I think the watch option might be useful when using ezdxf to generate a file. The viewer can be kept open and will update whenever you re-run your script that generates the file
=> Reload and watch

src/ezdxf/entities/dxfgfx.py
Let `msp` be the model space of some dxf document in which the font of the "Standard" text style is "OpenSans-Regular.ttf" (for example), rather than the more usual "txt".  Then, `ezdxf.entities.dxfgfx.get_font_name(msp.add_text("HELLO WORLD))` incorrectly returns "txt".  It ought to return "OpenSans-Regular.ttf".
I think the cleanest fix to this problem is to change the way `ezdxf.entities.dxfgfx.get_font_name()` determines whether entity "has" (in some sense) a style.  We should not use `entity.dxf.hasattr("style")`, which will return False if entity happens to be an ezdxf.entities.text.Text object that has not had its style explicitly set.  Instead, we should use  `entity.dxf.is_supported("style")`, which will return true for  an implicitly-Standard-style Text object.  The program flow …
=> Changed ezdxf.entities.dxfgfx.get_font_name() to correctly handle implicitly-styled Text entities

src/ezdxf/path/shapes.py
There seems to be a missing minus sign in the `ezdxf.path.rect()` function.  As a result, the final vertex is the upper-right corner, not the expected lower-right corner, and you end up with a right triangle instead of the expected rectangle.   I have fixed the problem by adding the missing minus sign.
=> fixed a typo in ezdxf.path.rect()

docs/source/dxfobjects/mleaderstyle.rst
ref: `src/ezdxf/render/mleader.py`
=> Correct attribute name: landing_gap_size

docs/source/dxfobjects/mleaderstyle.rst
=> Revert "Correct attribute name: landing_gap_size"

src/ezdxf/addons/drawing/config.py, src/ezdxf/addons/drawing/file_output.py, src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/pymupdf.py, src/ezdxf/commands.py
as part of fixing the svg and mupdf backends I wanted a way to *use* the backends. I have abstracted the file output logic from the ezdxf draw command so now all the backends can be used with ezdxf draw:
- **matplotlib**: bitmap and vector
- **qt**: bitmap and vector (svg) (the output is created without opening a GUI)
- **mupdf**: bitmap and vector
- **custom_svg**: vector (svg)
use with `ezdxf draw <dxf_path> -o <out_path> --backend <backend>`
this may be useful for development (to compare outputs between backends) and also may be useful for users because one backend may give the result that they want while another might not. Also one backend may be faster than another.
=> Improve draw command

docs/source/addons/pycsg.rst
Update the old name ``MeshBuilder.render`` to ``MeshBuilder.render_mesh`` in PyCSG doc.
By the way, the performance of PyCSG in the doc seems outdated. I ran the example "Menger Sponge Level 3 vs Sphere" (on a laptop with Core i5-8250U @ 3.4GHz, Windows 10, CPython 3.8.1, ezdxf 1.1.4) and the runtime is about 8.5 seconds, which is much faster than the 60 seconds mentioned in the doc.
=> Update old name in PyCSG doc

src/ezdxf/tools/clipping_portal.py
Fixes a typo in the names of the `ClippingShape.is_completley_inside` and `ClippingShape.is_completley_outside` methods: “`completley`” should be “`completely`.”
=> Fix ClippingShape.is_completely_{inside,outside} spelling

src/ezdxf/units.py, tests/test_05_tools/test_500_units.py
=> Fix units.unit_name to work on Python 3.11 or later

src/ezdxf/addons/drawing/frontend.py, src/ezdxf/addons/drawing/layout.py, src/ezdxf/addons/drawing/properties.py, src/ezdxf/addons/drawing/pymupdf.py, src/ezdxf/commands.py
This PR introduces the option for the muPDF backend to tag entities as belonging to 'optional content groups' which are similar to layers in that visibility of entities in the groups can be toggled in supported viewers. [muPDF OCG documentation](https://pymupdf.readthedocs.io/en/latest/recipes-optional-content.html). This feature was requested in #1154 .
The current implementation only outputs visible layers as entities on invisible/hidden layers are filtered out by the frontend. A future improvement could be to use `--all-layers-visible` together with an option for the backend to set the layer visibility in the output independently from their visibility in the dxf.
Some fixes have also been applied to the `ezdxf draw` command as the `--all-layers-visible` had stopped working.
=> Optional content groups in muPDF backend

src/ezdxf/render/mline.py
Based on [this bug report](https://github.com/mozman/ezdxf/issues/1167). I think this is a pretty trivial fix, but if I'm mistaken please do let me know!
=> Fix mline.py crash due to passing int instead of float

src/ezdxf/math/rtree.py
Should generally be slightly faster. Lmk if you're interested in benchmarks backing up my thinking though.
=> Use `operator.itemgetter` instead of a custom lambda in `ezdxf.math.rtree.box_split`

src/ezdxf/entities/insert.py
It is probably intuitive to assign a default value from the block (attribute) definition.
=> Insert.add_auto_attribs() support default values

src/ezdxf/entities/dxfns.py, tests/test_10_issues/test_issue_1231_pickling.py
fixes https://github.com/mozman/ezdxf/issues/1231
`DXFNamespace` has custom `__getattr__` and `__setattr__` so the default pickling mechanism doesn't work. Instead, custom state management is implemented for `DXFNamespace`. The unit test attempts to pickle and unpickle every example dxf. On my machine this takes ~3 seconds.
Pickling may be useful to cache parse results or to send dxf documents to subprocesses in a multiprocessed application.
=> add support for pickling DXF entities

src/ezdxf/addons/drawing/pymupdf.py
Each drawing operation previously created and committed a new shape, causing significant performance overhead. This update introduces a shared shape instance reused across operations and committed once in finalize().
This change was inspired by a suggestion from the PyMuPDF maintainer in pymupdf/PyMuPDF#3800. Performance improvements can exceed 100x in documents with many entities.
=> Optimize shape handling in PyMuPdfRenderBackend

src/ezdxf/addons/geo.py, tests/test_08_addons/test_813_geo_interface.py
This pull request adds support for exporting the `z` component of the geometries when calling the `__geo_interface__` method of the `GeoProxy` object.
If the entity contains at least one non-zero `z` component, it is interpreted as a 3D object, and the coordinates will be exported as `tuple[float, float, float]`.
=> Add support for elevations in GeoProxy.__geo_interface__

src/ezdxf/addons/drawing/svg.py
When using the matplotlib backend, it is possible to easily convert coordinates in the DXF space to the output space: https://ezdxf.readthedocs.io/en/stable/howto/drawing-addon.html#how-to-get-the-pixel-coordinates-of-dxf-entities
This pull request saves the transformation matrix in an object variable on the `SVGBackend` to provide a similar functionality for this backend as well. 
Short example: `vector_in_svg_space = backend.transformation_matrix.transform(vector_in_dxf_space)`
I've been using this modification for a while and thought maybe it would be useful for others as well.
=> Make transformation matrix accessible on the SVGBackend
